import './styles.css';
import './wiki-overrides.css';
import { initBrainWindow } from './brain.js';
import { initScriptWriterWindow } from './scriptWriter.js';

const state = {
  activeWindow: 'script',
  games: [],
};

const tabs = [...document.querySelectorAll('[data-window-tab]')];
const panels = [...document.querySelectorAll('[data-window-panel]')];
const promptInput = document.querySelector('#wiki-prompt');
const gameSelect = document.querySelector('#game-select');
const askButton = document.querySelector('#ask-wiki');
const writeButton = document.querySelector('#write-script');
const errorMessage = document.querySelector('#error-message');
const statusBox = document.querySelector('#generation-status');
const statusLog = document.querySelector('#status-log');
const output = document.querySelector('#wiki-output');
const outputTitle = document.querySelector('#wiki-output-title');
const outputMeta = document.querySelector('#wiki-output-meta');
const outputBody = document.querySelector('#wiki-output-body');
const scriptWindow = document.querySelector('#script-window');
const clearOutputButton = document.querySelector('#clear-output');

function setWindow(windowName) {
  state.activeWindow = windowName;

  for (const tab of tabs) {
    tab.classList.toggle('active', tab.dataset.windowTab === windowName);
  }

  for (const panel of panels) {
    panel.hidden = panel.dataset.windowPanel !== windowName;
  }

  if (windowName === 'brain') {
    void initBrainWindow();
  }

  if (windowName === 'script-writer') {
    void initScriptWriterWindow();
  }
}

function showError(message) {
  errorMessage.textContent = message;
  errorMessage.hidden = !message;
}

function setLoading(message, isLoading) {
  statusLog.textContent = message || '';
  statusBox.hidden = !isLoading;
  scriptWindow.classList.toggle('is-working', isLoading);
  askButton.disabled = isLoading;
  writeButton.disabled = isLoading;
}

function setResultVisible(isVisible) {
  output.hidden = !isVisible;
  scriptWindow.classList.toggle('has-result', isVisible);
}

async function requestJson(url, body) {
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const data = await response.json();

  if (!response.ok) {
    throw new Error(data.error || 'Request failed.');
  }

  return data;
}

function sceneText(scene, mode = 'ugc') {
  if (mode === 'storytelling') {
    const text = [
      `SC${scene.scene_number || ''} - ${scene.setting || 'Scene'}`,
      (scene.scene_description || scene.description)
        ? `Story: ${scene.scene_description || scene.description}`
        : '',
      (scene.narration || scene.vo) ? `Narration: ${scene.narration || scene.vo}` : '',
    ].filter(Boolean).join('\n');

    return text.trim() ? text : JSON.stringify(scene, null, 2);
  }

  const text = [
    `SC${scene.scene_number || ''} - ${scene.description || scene.setting || 'Scene'}`,
    (scene.vo || scene.narration) ? `VO: ${scene.vo || scene.narration}` : '',
    scene.action ? `Action: ${scene.action}` : '',
    scene.screen ? `Screen: ${scene.screen}` : '',
  ].filter(Boolean).join('\n');

  return text.trim() ? text : JSON.stringify(scene, null, 2);
}

function scriptMode(result, scenes) {
  if (result.mode === 'storytelling' || result.mode === 'ugc') {
    return result.mode;
  }

  // Backward compatibility for a response generated by a newer storytelling backend while an
  // older server omitted the mode field. Scene shape is authoritative enough to render the text.
  return scenes.some((scene) => (
    'scene_description' in scene
    || 'setting' in scene
    || 'narration' in scene
    || 'characters' in scene
  )) ? 'storytelling' : 'ugc';
}

/**
 * Asset bytes come through the wiki, not straight from the finder: the finder's asset routes are
 * gated by ASSET_ACCESS_TOKEN and the browser must never hold that token. Falls back to the raw URL
 * when the asset id is missing.
 */
function assetProxyUrl(asset, variant, { download = false } = {}) {
  if (!asset?.assetId) {
    return variant === 'preview' ? asset?.previewUrl : asset?.imageUrl;
  }

  return `/api/asset-proxy/${encodeURIComponent(asset.assetId)}/${variant}${download ? '?download=1' : ''}`;
}

/**
 * The ad's asset set, flat rather than per scene. Whatever rows remain here are what the handoff
 * carries, so Remove and Replace both persist before the row changes.
 */
function renderAssetBlock(assets, runId, { gameId = null, game = null } = {}) {
  const block = document.createElement('article');

  block.className = 'wiki-script-scene wiki-asset-block';

  const heading = document.createElement('p');

  heading.className = 'wiki-asset-heading';
  block.append(heading);

  const list = document.createElement('div');

  list.className = 'wiki-asset-list';
  block.append(list);

  let current = [...assets];

  function setHeading(message) {
    heading.textContent = message
      || `Assets (${current.length}) — these are what get sent`;
  }

  async function act(verb, asset) {
    if (!runId) {
      setHeading('Cannot change the set — no run id');
      return null;
    }

    setHeading(`${verb === 'remove' ? 'Removing' : 'Replacing'} ${asset.fileName}...`);

    try {
      const response = await fetch(`/api/runs/${encodeURIComponent(runId)}/assets/${verb}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ assetId: asset.assetId, gameId, game }),
      });
      const data = await response.json();

      if (!response.ok) {
        setHeading(`Could not ${verb} — ${data.error || 'request failed'}`);
        return null;
      }

      current = data.selection.selected;
      paint();
      setHeading(verb === 'remove'
        ? `Removed ${asset.fileName} — ${current.length} asset(s) will be sent`
        : `Replaced ${data.replaced.fileName} with ${data.with.fileName}`);

      return data;
    } catch (error) {
      setHeading(`Could not ${verb} — ${error.message}`);
      return null;
    }
  }

  function row(asset) {
    const item = document.createElement('div');

    item.className = 'wiki-asset-row';

    const thumb = document.createElement('img');

    thumb.className = 'wiki-asset-thumb';
    // Served through the wiki so the finder's asset token never reaches the browser.
    thumb.src = assetProxyUrl(asset, 'preview');
    thumb.alt = asset.fileName || 'asset';
    thumb.loading = 'lazy';
    item.append(thumb);

    const label = document.createElement('div');

    label.className = 'wiki-asset-label';

    const name = document.createElement('strong');

    name.textContent = asset.fileName || asset.assetId;
    label.append(name);

    const facts = document.createElement('small');

    facts.textContent = [
      // Storytelling binds one asset per cast member; UGC sources per beat and leaves this null.
      asset.character ? `for ${asset.character.split(/\s+[-–—:]\s+/)[0]}` : '',
      asset.folder || '',
      typeof asset.score === 'number' ? `score ${asset.score.toFixed(3)}` : '',
    ].filter(Boolean).join('  ·  ');
    label.append(facts);
    item.append(label);

    const actions = document.createElement('div');

    actions.className = 'wiki-asset-links';

    for (const [text, href] of [
      ['Preview', assetProxyUrl(asset, 'preview')],
      ['Download', assetProxyUrl(asset, 'file', { download: true })],
    ]) {
      const link = document.createElement('a');

      link.className = 'wiki-beat-link';
      link.href = href;
      link.target = '_blank';
      link.rel = 'noopener noreferrer';
      link.textContent = text;
      actions.append(link);
    }

    for (const [text, verb, extraClass] of [
      ['Replace', 'replace', ''],
      ['Remove', 'remove', 'is-danger'],
    ]) {
      const button = document.createElement('button');

      button.type = 'button';
      button.className = `wiki-beat-link wiki-asset-action ${extraClass}`.trim();
      button.textContent = text;
      button.addEventListener('click', () => void act(verb, asset));
      actions.append(button);
    }

    item.append(actions);

    return item;
  }

  function paint() {
    list.innerHTML = '';

    for (const asset of current) {
      list.append(row(asset));
    }

    setHeading();
  }

  paint();

  return block;
}

function renderScript(result) {
  const script = result.script || {};
  const scenes = Array.isArray(script.scenes) ? script.scenes : [];
  const sfx = Array.isArray(script.background_sfx) ? script.background_sfx : [];
  const mode = scriptMode(result, scenes);
  outputTitle.textContent = mode === 'storytelling'
    ? 'Storytelling script written'
    : 'UGC script written';
  outputMeta.textContent = [
    result.writer ? `Writer: ${result.writer}` : '',
    result.model ? `Model: ${result.model}` : '',
    // Why this brief went to this writer, so a surprising route is debuggable from the UI.
    result.routing?.reason ? `Routed: ${result.routing.reason}` : '',
  ].filter(Boolean).join(' · ');

  if (result.runId) {
    const handoff = document.createElement('a');

    handoff.className = 'wiki-handoff-link';
    handoff.href = `/api/runs/${encodeURIComponent(result.runId)}/handoff`;
    handoff.target = '_blank';
    handoff.rel = 'noopener noreferrer';
    handoff.textContent = 'handoff.json';
    outputMeta.append(' · ', handoff);
  }

  outputBody.innerHTML = '';

  if (mode === 'storytelling') {
    const block = document.createElement('pre');
    const storyContract = {
      characters: Array.isArray(script.characters) ? script.characters : [],
      scenes: scenes.map((scene) => ({
        scene_number: scene.scene_number,
        setting: scene.setting,
        scene_description: scene.scene_description,
        narration: scene.narration,
      })),
    };

    block.className = 'wiki-script-scene wiki-story-json';
    block.textContent = JSON.stringify(storyContract, null, 2);
    outputBody.append(block);
  } else {
    for (const scene of scenes) {
      const block = document.createElement('article');
      block.className = 'wiki-script-scene';
      block.textContent = sceneText(scene, mode);
      outputBody.append(block);
    }
  }

  if (mode !== 'storytelling' && sfx.length) {
    const block = document.createElement('article');
    block.className = 'wiki-script-scene';
    block.textContent = `Background SFX\n${sfx.map((item) => `- ${item}`).join('\n')}`;
    outputBody.append(block);
  }

  // Assets are their own block after Background SFX and styled the same way. Ad-level, not per scene.
  const assets = result.assetSelection?.selected || [];

  if (assets.length) {
    outputBody.append(renderAssetBlock(assets, result.runId, {
      gameId: result.gameId,
      game: result.catalogGame,
    }));
  } else if (mode === 'storytelling') {
    const block = document.createElement('article');

    block.className = 'wiki-script-scene wiki-asset-block';
    block.textContent = `Asset Finder\n${result.assetFinderError || 'No matching catalog assets were returned.'}`;
    outputBody.append(block);
  }

  setResultVisible(true);
}

function renderAnswer(result) {
  const answer = result.answer || {};

  outputTitle.textContent = answer.title || 'Wiki answer';
  outputMeta.textContent = result.model ? `Model: ${result.model}` : '';
  outputBody.innerHTML = '';

  const answerBlock = document.createElement('article');
  answerBlock.className = 'wiki-answer-block';
  answerBlock.textContent = answer.answer || '';
  outputBody.append(answerBlock);

  if (Array.isArray(answer.used_memory) && answer.used_memory.length) {
    const memoryBlock = document.createElement('article');
    memoryBlock.className = 'wiki-memory-used';
    memoryBlock.innerHTML = '<strong>Memory used</strong>';

    for (const item of answer.used_memory) {
      const line = document.createElement('p');
      line.textContent = `${item.section || 'Memory'} / ${item.group || 'Group'} - ${item.reason || ''}`;
      memoryBlock.append(line);
    }

    outputBody.append(memoryBlock);
  }

  setResultVisible(true);
}

function clearOutput() {
  outputBody.innerHTML = '';
  outputTitle.textContent = 'Wiki answer';
  outputMeta.textContent = '';
  setResultVisible(false);
  showError('');
}

async function loadGames() {
  const response = await fetch('/api/games');
  const data = await response.json();

  state.games = Array.isArray(data.games) ? data.games : [];
  gameSelect.innerHTML = '';

  for (const game of state.games) {
    const option = document.createElement('option');
    option.value = game.id;
    option.textContent = game.name || game.id;
    gameSelect.append(option);
  }

  if (!state.games.length) {
    const option = document.createElement('option');
    option.value = 'VIPBaloot';
    option.textContent = 'VIP Baloot';
    gameSelect.append(option);
  }
}

async function askWiki() {
  const question = promptInput.value.trim();

  showError('');

  if (!question) {
    showError('Write a question first.');
    return;
  }

  setLoading('Searching the wiki...', true);

  try {
    renderAnswer(await requestJson('/api/ask-wiki', {
      gameId: gameSelect.value,
      question,
    }));
  } catch (error) {
    showError(error.message);
  } finally {
    setLoading('', false);
  }
}

async function writeScript() {
  const userBrief = promptInput.value.trim();

  showError('');

  if (!userBrief) {
    showError('Write a script brief first.');
    return;
  }

  setLoading('Writing the script...', true);

  try {
    renderScript(await requestJson('/api/write-script', {
      gameId: gameSelect.value,
      userBrief,
    }));
  } catch (error) {
    showError(error.message);
  } finally {
    setLoading('', false);
  }
}

for (const tab of tabs) {
  tab.addEventListener('click', () => setWindow(tab.dataset.windowTab));
}

askButton.addEventListener('click', askWiki);
writeButton.addEventListener('click', writeScript);
clearOutputButton.addEventListener('click', clearOutput);
promptInput.addEventListener('keydown', (event) => {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault();
    writeScript();
  }
});

await loadGames();
